### ISSUE TITLE
Input should be switched to a c# stack instead of a list

### ISSUE THREAD

**Issue by TimyJ** [TimyJ/GrimDank#2]
What it says. Otherwise we are calling inputHandlers.reversed

**Comment by Chris3606** [comment]
Do we want to enforce that we can only remove input handlers in the reverse order that they were added?  Since you can't pop arbitrary elements from a C# stack, this would be the case if we switched.

If that is not a restriction we want, I can simply reverse the order of iteration over list items.

**Comment by TimyJ** [comment]
Undefined. So returning in reverse order may be better

**Comment by Chris3606** [comment]
Agreed.  Merged to master.
