### ISSUE TITLE
Modify project to compile without MonoGame SDK installed

### ISSUE THREAD

**Issue by Chris3606** [TimyJ/GrimDank#3]
Because of MonoGame specific template set-up, the current project will not compile unless the MonoGame SDK is installed (on a Windows computer; linux is fine because of how MonoGame installs to begin with).  This may be unavoidable, however it might be worth looking into seeing if it can be made more portable.

**Comment by TimyJ** [comment]
If we can fix it easy then yeah. Otherwise having a build dependency isn't the worst. Keeping this on the back burner unless you have other thoughts

**Comment by Chris3606** [comment]
I've got no plans to pursue a fix anytime soon. Really I just wanted to note it, as I discovered it trying to set up on a new computer.

**Comment by TimyJ** [comment]
We can roll this into the switch to Monogame .NET core
