### ISSUE TITLE
Refactor Input to Take Key and ModifierState

### ISSUE THREAD

**Issue by TimyJ** [TimyJ/GrimDank#5]
Should create a custom struct ala TCOD_key_t for example: 

```
struct InputState {
    int Key;
    bool Tab;
    bool Shift;
    bool Alt;
    bool Ctrl;
}
```

This could be solved by looping through all keys and setting the Key field to the first one found, then if any modifiers are solved using that. This would simplify greatly the use of modifier keys as well as abstracting away left and right versions of those keys from game code that handles input.

**Comment by Chris3606** [comment]
Will change HandleKeyboard(KeyboardState) to HandleKeyboard(Key, Modifiers), and it will handle each key separately in this manner.

**Comment by Chris3606** [comment]
Going to split this into 2 things given to HandleKeyboard - (Keys key, ModifierState modfierState).  This allows slightly less work to keep track of modifiers because of how InputStack works.

**Comment by TimyJ** [comment]
Good idea.

**Comment by Chris3606** [comment]
Should tab be a modifier key?  I would think not, since it's not likely to be used as a modfier for another non-modifier key?

**Comment by Chris3606** [comment]
Tab is not tracked as a modifier key, particularly with the current method nto supporting "hold button to activate" style input.
