### ISSUE TITLE
Code cleanup/Ease of Use

### ISSUE THREAD

**Issue by Chris3606** [TimyJ/GrimDank#6]
Really this is just an issue to marshal things that look difficult to do in the current setup, or general code cleanup items/suggestions that aren't big enough deals to be issues themselves, as we go along.  It will likely be edited frequently, and none of this is much of a rush, more for the sake of readability and/or ease of use:

* A lot of foreach loops over entities on layers when it is known the layer only has at most 1 entity per positiion, could be condensed down using IEnumerable<T>.SingleOrDefault().
   * This function call ends up being somewhat long: `GrimDank.Instance.TestLevel.GetLayers(Map.Layers.CREATURES).GetItems(position).SingleOrDefault()`.  Furthermore is not technically precise because if an error is made it requires not only a violation to be possible, but to actually exist, in order to cause the error.  Thus we could write a function in map like `MObject GetItem(Map.Layer layer, Coord position)`, to get a sole item or null, immediately throwing an exception if the layer in question so much as supports multiple items on a tile (whether it actually contains multiple items at that time, or not.  Raycasting for this purpose is another alternative, but is slightly inefficient.
* Eventually we should establish/implement naming conventions throughout the project. Exceptionally minor, but may seek to improve readability once large-scale expansion begins.
* `WalkabilityProvider` and `ResistanceProvider` classes could be removed, and switched with one-liner initializations using `GoRogue.LambdaMapView`.  Unless their functionality is likely to expand, it would condense file-spread.

**Comment by TimyJ** [comment]
Approve everything except the map providers. Not enough functionality is known to be worth removing to add them again unless performance is relevant

**Comment by Chris3606** [comment]
Performance should not be drastically effected either way.  I had considered potential for addition as well, although to be honest it seems very unlikely.  The providers themselves currently only call `Map.IsWalkable()` or `Map.IsTransparent()` anyway, and it would seem those functions in Map would be more likely to change, vs. the providers themselves.  In any case, your call.

The naming conventions we'll have to discuss in a separate issue or post in the wiki somewhere or some such.  The forwarder function for single item layers I'll put on my todo list.

**Comment by Chris3606** [comment]
`GetSoleItem` is up and used in appropriate places (pretty sure I got all of them) on master.

**Comment by Chris3606** [comment]
Complete.  In the future its probably better to make a label tag cleanup, and just make separate issues?
