### ISSUE TITLE
InputHandling and Map Seem Not To Mix?

### ISSUE THREAD

**Issue by Chris3606** [TimyJ/GrimDank#8]
Currently a lot of our (player) input-handling is in map.... But looking at the code, it seems the code would be more readable if we moved the input to player (all you GrimDank.Instance.Player.X.... calls become CurrentMap.X.

Probably we should pull it into a class attached to our Player class, then however we handle turns will decide stuff -- turn "handling" for the player can just add/remove that input handler, or be the input handler itself.

**Comment by TimyJ** [comment]
Take a step further and add an so component to MObjects. Players ai component handles input and this is good

**Comment by Chris3606** [comment]
AI component is doable.  This begs the question, do we wish to implement turn-taking at this time?  Also I would think AI would be component of Creature (Rather than base MObject), though completely inconsequential.

**Comment by Chris3606** [comment]
This is up on my dev branch.
