### ISSUE TITLE
Map and MapExtensions Distinguishing Factors

### ISSUE THREAD

**Issue by Chris3606** [TimyJ/GrimDank#9]
The distinguishment as to what is in/supposed to be in Map vs MapExtensions is... clear as 30 feet of mud....

Perhaps we should consider some renames or moving things around to make this easier :D

**Comment by TimyJ** [comment]
A lot of this is pretty placeholder. At the end of today will have a more grounded approach and an architecture google doc/page on the wiki will be created. Will close this when that is up and running. #6 also addresses naming conventions and this will be covered in that as well. Considering this closed FTM
